package com.event.domain;
// Generated 2017-6-11 9:12:32 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Integer userId;
	private String userRealname;//真实姓名
	private String userPassword;
	private Integer userPriviliage;//权限
	private String userName;
	private String userPhone;
	private String userEmail;
	private String userZt;//����״̬
	private Integer userMember;
	private Integer userMax;
	private Integer userComplete;
	private Integer userDepartfb;
	private Integer userUserfb;
	private Set TEventsForEventCommitId = new HashSet(0);
	private Set TTalksForKehuId = new HashSet(0);
	private Set TEventsForKefuId = new HashSet(0);
	private Set TRecords = new HashSet(0);
	private Set TTalksForKefuId = new HashSet(0);
	private Set TEventsForLeadId = new HashSet(0);
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public String getUserRealname() {
		return userRealname;
	}
	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}
	public String getUserPassword() {
		return userPassword;
	}
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}
	public Integer getUserPriviliage() {
		return userPriviliage;
	}
	public void setUserPriviliage(Integer userPriviliage) {
		this.userPriviliage = userPriviliage;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getUserPhone() {
		return userPhone;
	}
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}
	public String getUserEmail() {
		return userEmail;
	}
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
	public String getUserZt() {
		return userZt;
	}
	public void setUserZt(String userZt) {
		this.userZt = userZt;
	}
	public Integer getUserMember() {
		return userMember;
	}
	public void setUserMember(Integer userMember) {
		this.userMember = userMember;
	}
	public Integer getUserMax() {
		return userMax;
	}
	public void setUserMax(Integer userMax) {
		this.userMax = userMax;
	}
	public Integer getUserComplete() {
		return userComplete;
	}
	public void setUserComplete(Integer userComplete) {
		this.userComplete = userComplete;
	}
	public Integer getUserDepartfb() {
		return userDepartfb;
	}
	public void setUserDepartfb(Integer userDepartfb) {
		this.userDepartfb = userDepartfb;
	}
	public Integer getUserUserfb() {
		return userUserfb;
	}
	public void setUserUserfb(Integer userUserfb) {
		this.userUserfb = userUserfb;
	}
	public Set getTEventsForEventCommitId() {
		return TEventsForEventCommitId;
	}
	public void setTEventsForEventCommitId(Set tEventsForEventCommitId) {
		TEventsForEventCommitId = tEventsForEventCommitId;
	}
	public Set getTTalksForKehuId() {
		return TTalksForKehuId;
	}
	public void setTTalksForKehuId(Set tTalksForKehuId) {
		TTalksForKehuId = tTalksForKehuId;
	}
	public Set getTEventsForKefuId() {
		return TEventsForKefuId;
	}
	public void setTEventsForKefuId(Set tEventsForKefuId) {
		TEventsForKefuId = tEventsForKefuId;
	}
	public Set getTRecords() {
		return TRecords;
	}
	public void setTRecords(Set tRecords) {
		TRecords = tRecords;
	}
	public Set getTTalksForKefuId() {
		return TTalksForKefuId;
	}
	public void setTTalksForKefuId(Set tTalksForKefuId) {
		TTalksForKefuId = tTalksForKefuId;
	}
	public Set getTEventsForLeadId() {
		return TEventsForLeadId;
	}
	public void setTEventsForLeadId(Set tEventsForLeadId) {
		TEventsForLeadId = tEventsForLeadId;
	}

	
	

}
